apiVersion: v1
kind: Namespace
metadata:
  name: shop-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: shop-v2
  labels:
    app: cart
spec:
  replicas: 2
  progressDeadlineSeconds: 45
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: nginx:1.27-alpine
